### ISSUE TITLE
File Name Input box always defaults to the first vDefaultFileName

### ISSUE THREAD

**Issue by Matheus-Garbelini** [aiekick/ImGuiFileDialog#26]
**Describe the bug**
This bug happens when opening a dialog window with a different default file name. The file name is always the previous one, hence the parameter vDefaultFileName of method OpenDialog only works once. I could not find documentation if this was intended by the author, so sorry if this is not classified as a BUG, but I'd like to know what would be the correct way to change the default file name every time the parameter vDefaultFileName is different.

**To Reproduce**
1. Simply perform a test, calling OpenDialog method with vDefaultFileName different in a posterior call:
**string file_name = "file1";**
igfd::ImGuiFileDialog::Instance()->OpenDialog("dialog1", "BUG REPORT", ".json", "relative/path/", file_name);
// Later on the code, same line, but different default file name:
**string file_name = "file2";** // < ---- the issue, file2 is never shown as default file name in the dialog file name input box
igfd::ImGuiFileDialog::Instance()->OpenDialog("dialog1", "BUG REPORT", ".json", "relative/path/", file_name);

**Expected behavior**
File name: input box always defaults to the first vDefaultFileName "file_name1".

**Screenshots**
Not applicable since it's not a visual bug, but a functional one.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04

**Additional context**
Let me know if the explanation is enough. If you'd like I can provide a standalone example if you didn't get the steps, but simply changing the vDefaultFileName with the example calls mentioned here is enough to see that the default file name input box does not change to match the second OpenDialog call.

**Possible fix**
An ugly workaround is shown below
```C++
void ImGuiFileDialog::SetPath(const std::string &vPath)
{
	m_CurrentPath.clear(); // < ---------- forcibly clearing this works???
	m_ShowDrives = false;
	m_CurrentPath = vPath;
	m_FileList.clear();
	m_CurrentPath_Decomposition.clear();
	ScanDir(m_CurrentPath);
}
```

**Comment by aiekick** [comment]
interesting, thanks. i will check that tonight.

btw i dont understand your fix, because m_CurrentPath  is replaced by vPath just after.

**Comment by Matheus-Garbelini** [comment]
hi, @aiekick I understood what internally the script does and now fixed in a proper way.
Turns out that you use the following line to reset the default filename:
```C++
// Reset default file name
ResetBuffer(FileNameBuffer);
AppendToBuffer(FileNameBuffer, MAX_FILE_DIALOG_NAME_BUFFER, dlg_defaultFileName);
```
The issue is that the lines above are only called at specific places, which never resets the default filename when it changes.
I fixed by adding the above lines just before the `SetPath` from `OpenDialog` functions. 
However, because I understand you would still like to keep the previous file name or path changed by the user on the dialog file input, coding something like the following could work with proper adjustments:
```C++
void ImGuiFileDialog::OpenDialog(...){
...
  if (dlg_defaultFileName.compare(vDefaultFileName) != 0){
    // Whenever the caller has a different `vDefaultFileName`, reset the `FileNameBuffer`
    ResetBuffer(FileNameBuffer);
    AppendToBuffer(FileNameBuffer, MAX_FILE_DIALOG_NAME_BUFFER, dlg_defaultFileName);
  }
}
```

Let me know if the explanation above makes sense.
Regards and thanks for this great library.

**Comment by aiekick** [comment]
yes it make sense.
indeed it was i wanted to work like that.
this class can be call from many different places and with different settings. so put the default file to use is needed.
not fixed this long time bug haha
can you do a PR please ? thanks for your great help

**Comment by Matheus-Garbelini** [comment]
@aiekick sorry for the delay. Thanks a lot, this library was really useful.
